# Generated by Django 5.1.3 on 2025-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('nike', 'nike'), ('adidas', 'adidas')], default='nike', max_length=50),
        ),
    ]
